# Generated by Django 5.0.3 on 2024-11-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='lower',
            field=models.FloatField(blank=True, db_column='lower', default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='upper',
            field=models.FloatField(blank=True, db_column='upper', default=0),
        ),
    ]
