version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=sturm
      - DATABASE_USER=root
      - DATABASE_PASSWORD=
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: sturm
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3306:3306"
