# Generated by Django 5.0.3 on 2024-11-03 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('idStudent', models.IntegerField(blank=True, db_column='idStudent', default=0)),
                ('P0', models.TextField(blank=True, db_column='P0', default='0')),
                ('P1', models.TextField(blank=True, db_column='P1', default='0')),
                ('G', models.TextField(blank=True, db_column='G', default='0')),
                ('arr', models.TextField(blank=True, db_column='arr', default='0')),
                ('theory', models.TextField(blank=True, db_column='theory', default='0')),
                ('firstPoint', models.TextField(blank=True, db_column='firstPoint', default='0')),
                ('secondPoint', models.TextField(blank=True, db_column='secondPoint', default='0')),
                ('edges', models.TextField(blank=True, db_column='edges', default='0')),
                ('numOfZeros', models.TextField(blank=True, db_column='numOfZeros', default='0')),
                ('add1', models.TextField(blank=True, db_column='add1', default='0')),
                ('add2', models.TextField(blank=True, db_column='add2', default='0')),
                ('P0_original', models.TextField(blank=True, db_column='P0_original', default='0')),
                ('lower', models.IntegerField(blank=True, db_column='lower', default=0)),
                ('upper', models.IntegerField(blank=True, db_column='upper', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('idStudent', models.IntegerField(blank=True, db_column='idStudent', default=0)),
                ('idQuestion', models.IntegerField(blank=True, db_column='idQuestion', default=0)),
                ('time', models.DateTimeField(db_column='time', default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('idStudent', models.IntegerField(blank=True, db_column='idStudent', default=0)),
                ('points', models.IntegerField(blank=True, db_column='points', default=0)),
                ('index', models.IntegerField(blank=True, db_column='index', default=0)),
                ('time', models.DateTimeField(db_column='time', default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Searched',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('idStudent', models.IntegerField(blank=True, db_column='idStudent', default=0)),
                ('idHistory', models.IntegerField(blank=True, db_column='idHistory', default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UnansweredQuestions',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('idStudent', models.IntegerField(blank=True, db_column='idStudent', default=0)),
                ('idQuestion', models.IntegerField(blank=True, db_column='idQuestion', default=0)),
                ('time', models.DateTimeField(db_column='time', default=django.utils.timezone.now)),
            ],
        ),
    ]
